version: "3.8"
services:
  db:
    image: mysql:8.0.33
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynet

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    command: ["sh", "-c", "./wait-for-db.sh db 3306 && ./bin/api"]
    networks:
      - mynet

networks:
  mynet:
    driver: "bridge"
